#!/bin/bash
# Embed file in shell script.
#
# usage: script [OPTIONS] SCRIPT
#
# This script deals with file included in shell script between two surrounding
# lines of the form
#
#     # begin FILENAME ENC
#     # end FILENAME
#
# where ENC is optional and represents a specific encoding (base64).
#
# In order to avoid shell conflicts, these lines are generally inserted after
# an explicit 'exit 0'.
#
# If no action option is specified then '-l' is implied. If more than one is
# specified only the last one on command line is processed.
#
# OPTIONS
#     -a, --add FILE       embed FILE at the end of SCRIPT or by replacing the
#                          last '# include FILENAME' line by its content
#     -u, --update FILE    update the embedded FILE in SCRIPT
#     -U, --update-all     update all embedded files (must be in current dir)
#     -l, --list           list embedded files
#     -x, --extract FILE   extract FILE
#     -X, --extract-all    extract all files
#     -s, --shell          show shell functions to include in script
#     -b, --base64         use base64 instead of cat when adding
#     -h, --help           show this help message

# Copyright (C) 2016 Bruno BEAUFILS <bruno@boulgour.com>
#
# This software comes with ABSOLUTELY NO WARRANTY.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation in its version 2.
#
# See the README or COPYING file for details.

ACTION=list-files
ENCODE=

# doc is commented at the beggining of the script until first empty line
doc () { sed -n '2,/^$/ { s/^ *#// ; s/^ //g ; t ok ; d ; :ok ; p }' <$0 ; }

# die with an error message
die () { echo "$(basename $0): error: $*" 1>&2 ; exit 1 ; }

# run a command silently
mute () { 1>/dev/null 2>&1 $* ; }

# warn absence of $1, last parm may be used for listing needed debian packages
need () { die "$1 is unavailable" ; }

# verify if needed tools are available
vrfy ()
{
    mute which base64 || need base64
}

# add $2 in $1 eventually encoded as $3
add-file ()
{
    f=$(basename $2)

    if [ "x$3" = "xbase64" ] ; then
        t=$(mktemp)
        base64 "$2" > "$t"
        set "$1" "$t" "$3"
    fi

    l=$(sed -n '/^# include '"$f"' *$/ =' "$1" | tail -1)
    if [ -z "$l" ] ; then
        l='$' ; cmd=
    else
        cmd="-e ${l}d"
    fi

    sed -i \
        -e "$l"' a\# begin '"$f"' '"$3" \
        -e "$l"' r '$2\
        -e "$l"' a\# end '"$f" \
        $cmd \
        $1

    [ $t ] && rm $t 
}

# update $2 in $1
update-file ()
{
    f=$(basename $2)

    enc=$(sed -nr 's/^# begin '"$f"' (.*)$/\1/; t o; b; :o p' "$1")
    if [ "x$enc" = xbase64 ] ; then
        t=$(mktemp)
        base64 "$2" > "$t"
        set "$1" "$t"
    fi

    sed -i -r \
        -e '/^# begin '"$f"'($| .*$)/ a\# begin-tmp' \
        -e '/^# end '"$f"' *$/ i\# end-tmp' \
        "$1"
    sed -i -r \
        -e '/^# begin-tmp$/,/^# end-tmp$/ d' \
        -e '/^# begin '"$f"'($| .*$)/ r '"$2" \
        "$1"
        
    [ $t ] && rm $t 
}

# extract $2 from $1
extract-file ()
{
    enc=$(sed -nr 's/^# begin '"$2"' (.*)$/\1/; t o; b; :o p' "$1")
    cmd=cat
    [ x$enc = xbase64 ] && cmd="base64 -d"

    sed -nr '/^# begin '"$2"'($| .*$)/,/^# end '"$2"'$/ p' "$1" \
        | sed '1d ; $d' \
        | $cmd > "$2"
}

# list files embedded in $1
list-files () { grep '^# begin' $1 | sed -r -e 's/^# begin ([^ ]+)($| .*$)/\1/' ; }

# Args processing
while [ -n $1 ]
do
    case "$1" in
        "-a"|"--add") ACTION=add-file ; shift ; FILE=$1 ;;
        "-u"|"--update") ACTION=update-file ; shift ; FILE=$1 ;;
        "-U"|"--update-all") ACTION=update-all ;;
        "-l"|"--list") ACTION=list-files ;;
        "-x"|"--extract") ACTION=extract-file ; shift ; FILE=$1 ;;
        "-X"|"--extract-all") ACTION=extract-all ;;
        "-s"|"--shell") declare -f list-files extract-file ; exit 0 ;;
        "-b"|"--base64") ENCODE=base64 ;;
        "-h"|"--help") doc ; exit 0 ;;
        *) break ;;
    esac
    shift
done
SCRIPT=$1

# Common checks
vrfy || die "needed tools are missing"
[ -z $SCRIPT ] && die "no script specified"

# Action
case "$ACTION" in
    "add-file"|"update-file")
        [ -z "$FILE" ] && die "no file specified"
        [ ! -r "$FILE" ] && die "cannot read $FILE"
        $ACTION "$SCRIPT" "$FILE" "$ENCODE"
        ;;
    "extract-file")
        [ -z "$FILE" ] && die "no file specified"
        $ACTION "$SCRIPT" "$FILE"
        ;;
    "update-all")
        list-files "$SCRIPT" | while read file
        do
            update-file "$SCRIPT" "$file"
        done
        ;;
    "extract-all")
        list-files "$SCRIPT" | while read file
        do
            extract-file "$SCRIPT" "$file"
        done
        ;;
    "list-files"|*)
        list-files "$SCRIPT"
        ;;
esac
